sudo: false
language: python

services:
  - mysql

install:
  - pip install tox

matrix:
  include:
    - stage: test
      python: 3.3
      env: TOX_ENV=py33
    - stage: test
      python: 3.4
      env: TOX_ENV=py34
    - stage: test
      python: 3.5
      env: TOX_ENV=py35
    - stage: test
      python: 3.6
      env: TOX_ENV=py36

script:
  - tox -e $TOX_ENV
