sudo: false
language: python

services:
  - mysql

install:
  - pip install tox

matrix:
  include:
    - stage: test
      python: 2.7
      env: TOX_ENV=py27
    - stage: test
      python: 3.4
      env: TOX_ENV=py34
    - stage: test
      python: 3.5
      env: TOX_ENV=py35
    - stage: test
      python: 3.6
      env: TOX_ENV=py36
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: mattbennett
        password:
          secure: "x27Zk+mvbYOtuf3XojYBh3O32KTv79SebMzkXE1lmtSms/pvRT+OG5eUAvWq1tro0shQdvv1X86aK9UHNzkRpIJEvbyH8zP3nWr/TlI62iZJC6y9m/c6JWwIUBk3p+CDHSwA1i6QXrxnffRfE/KSlAuTOY2FDYFDUBdVrEQrqIJa68Ij9200kxNcYWC9JmJKLaGl1l/V9M2K7YDsll3PxBByrCQeM95oeuoL3U81fPV0CJnsPNXAMtQHC9+dv+WE9UCo9QVsxWrnJGvCVUAfNQ7Ub+pECwSqzIL1O1ltqi0JH5CafwF6EMcQWxjh6R7IuN224QoAGTBzJ+ngKMxV7aQr58rkP82CyGaYEI7w9pvM9cZ6nBVIdgfCe8EfXCg+tTYy6v7SptT66wzP+GdX7sOuNFDYadmXGHZdwtUtEDFHwiCETRJNt/t5ONejlktY0fXlRUCta5UbYj755iryhk1lE7Ldj3sU336WjG74iAFdAd0fO8gVM0OwKLYZeaU2mN4JBI4qcp6n2S0sNtoyqXzm9OL/76Is5vAzUQavto9ao9bw0HN+ZWVLyE4+NLKS3ti+Pi/YofieoUFZ6kQJQRGja3tt7RCl0MYHqdIQQWx9MJWdiDpkyqqtR+0Q2sSYo8g4TsJe8zCuQLOflwd9pLKXVwdfqMUVGFCbdzZ/rig="
        on:
          tags: true
          repo: Overseas-Student-Living/sqlalchemy-filters
        distributions: "sdist bdist_wheel"

script:
  - tox -e $TOX_ENV
