name: Tests CI
on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.tox }}
    runs-on: ubuntu-20.04

    services:
      mariadb:
        image: mariadb:10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: test_sqlalchemy_filters
          POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    strategy:
      fail-fast: false
      matrix:
        include:
          # sqlalchemylatest (i.e. > 2.0.0) is not yet supported
          # for any version of python

          - {python: '3.7', tox: "py37-sqlalchemy1.0"}
          - {python: '3.7', tox: "py37-sqlalchemy1.1"}
          - {python: '3.7', tox: "py37-sqlalchemy1.2"}
          - {python: '3.7', tox: "py37-sqlalchemy1.3"}
          - {python: '3.7', tox: "py37-sqlalchemy1.4"}

          - {python: '3.8', tox: "py38-sqlalchemy1.0"}
          - {python: '3.8', tox: "py38-sqlalchemy1.1"}
          - {python: '3.8', tox: "py38-sqlalchemy1.2"}
          - {python: '3.8', tox: "py38-sqlalchemy1.3"}
          - {python: '3.8', tox: "py38-sqlalchemy1.4"}

          - {python: '3.9', tox: "py39-sqlalchemy1.0"}
          - {python: '3.9', tox: "py39-sqlalchemy1.1"}
          - {python: '3.9', tox: "py39-sqlalchemy1.2"}
          - {python: '3.9', tox: "py39-sqlalchemy1.3"}
          - {python: '3.9', tox: "py39-sqlalchemy1.4"}

          # python3.10 with sqlalchemy <= 1.1 errors with:
          # AttributeError: module 'collections' has no attribute 'MutableMapping'
          - {python: '3.10', tox: "py310-sqlalchemy1.2"}
          - {python: '3.10', tox: "py310-sqlalchemy1.3"}
          - {python: '3.10', tox: "py310-sqlalchemy1.4"}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - run: pip install tox~=3.28
      - run: tox -e ${{ matrix.tox }}
